name: fcm_shared_isolate
description: Firebase Messaging Plugin for Flutter supporting shared isolate
homepage: https://famedly.com
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  firebase_core: 3.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.famedly.fcm_shared_isolate
        pluginClass: FcmSharedIsolatePlugin
      ios:
        pluginClass: FcmSharedIsolatePlugin
